services:
  # ------------------------------
  # データベース用コンテナ
  # ------------------------------
  postgres:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # ------------------------------
  # Django アプリケーション
  # ------------------------------
  web:
    build:
      context: .
    container_name: django_app
    env_file:
      - .env
    volumes:
      - ./app:/app:cached
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8888"
    # 権限をホストと合わせる
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    networks:
      - app-network

volumes:
  postgres_data:
    name: template_project_postgres_data

networks:
  app-network:
    driver: bridge
